export type TransactionStatus = 'Processing' | 'In Transit' | 'Completed';
export type ComplaintStatus = 'Pending' | 'In Progress' | 'Resolved' | 'Closed' | 'Rejected';
export type VerificationStatus = 'Pending' | 'Approved' | 'Rejected';

export const transactions = [
  {
    id: 'TXN-1024',
    farmer: 'Rahul Verma',
    company: 'GreenFresh Foods',
    crop: 'Basmati Rice',
    amount: '₹92,400',
    status: 'Processing' as TransactionStatus,
    date: '2026-07-12',
    farmerDetails: 'Rahul Verma · Kharif Village',
    companyDetails: 'GreenFresh Foods · Bengaluru',
    quantity: '1,200 kg',
    purchasePrice: '₹76/kg',
    pickupLocation: 'Mysuru, Karnataka',
    destinationLocation: 'Bengaluru, Karnataka',
    logistics: 'AgriCare Logistics',
  },
  {
    id: 'TXN-1059',
    farmer: 'Suma Nair',
    company: 'NatureHarvest',
    crop: 'Tomatoes',
    amount: '₹34,200',
    status: 'In Transit' as TransactionStatus,
    date: '2026-07-18',
    farmerDetails: 'Suma Nair · Nedumangad',
    companyDetails: 'NatureHarvest · Kochi',
    quantity: '780 kg',
    purchasePrice: '₹42/kg',
    pickupLocation: 'Nedumangad, Kerala',
    destinationLocation: 'Kochi, Kerala',
    logistics: 'Mitra Freight',
  },
  {
    id: 'TXN-1088',
    farmer: 'Karthik Rao',
    company: 'AgriPure',
    crop: 'Maize',
    amount: '₹58,900',
    status: 'Completed' as TransactionStatus,
    date: '2026-07-22',
    farmerDetails: 'Karthik Rao · Bellary',
    companyDetails: 'AgriPure · Hyderabad',
    quantity: '1,800 kg',
    purchasePrice: '₹30/kg',
    pickupLocation: 'Bellary, Karnataka',
    destinationLocation: 'Hyderabad, Telangana',
    logistics: 'Astra Logistics',
  },
];

export const farmers = [
  {
    id: 'FR-201',
    name: 'Rahul Verma',
    location: 'Mysuru, Karnataka',
    rating: 4.8,
    status: 'Active',
    village: 'Kharif Village',
    district: 'Mysuru',
    state: 'Karnataka',
    phone: '+91 98765 43210',
    email: 'rahul.verma@agri.com',
    totalEarnings: '₹2,40,000',
    cropsListed: 18,
    totalSales: '₹2.4L',
    cropTypes: ['Basmati Rice', 'Maize'],
    registrationDate: '2025-05-12',
  },
  {
    id: 'FR-215',
    name: 'Suma Nair',
    location: 'Nedumangad, Kerala',
    rating: 4.6,
    status: 'Active',
    village: 'Kudappanakkunnu',
    district: 'Thiruvananthapuram',
    state: 'Kerala',
    phone: '+91 99887 66554',
    email: 'suma.nair@agri.com',
    totalEarnings: '₹1,84,500',
    cropsListed: 12,
    totalSales: '₹1.8L',
    cropTypes: ['Tomatoes', 'Cucumbers'],
    registrationDate: '2025-09-08',
  },
  {
    id: 'FR-302',
    name: 'Karthik Rao',
    location: 'Bellary, Karnataka',
    rating: 4.9,
    status: 'Banned',
    village: 'Ibrahimpur',
    district: 'Bellary',
    state: 'Karnataka',
    phone: '+91 98989 34122',
    email: 'karthik.rao@agri.com',
    totalEarnings: '₹3,12,000',
    cropsListed: 26,
    totalSales: '₹3.1L',
    cropTypes: ['Maize', 'Groundnut', 'Wheat'],
    registrationDate: '2024-11-03',
  },
];

export const companies = [
  {
    id: 'CMP-409',
    name: 'GreenFresh Foods',
    location: 'Bengaluru, Karnataka',
    rating: 4.7,
    status: 'Active',
    companyType: 'Food Processor',
    licenseNumber: 'LIC-784512',
    email: 'support@greenfresh.in',
    phone: '+91 98800 12345',
    totalPurchases: '₹6.2L',
    totalSales: '₹8.5L',
    complaintCount: 2,
    registrationDate: '2025-01-09',
  },
  {
    id: 'CMP-512',
    name: 'NatureHarvest',
    location: 'Kochi, Kerala',
    rating: 4.5,
    status: 'Suspended',
    companyType: 'Agri Exporter',
    licenseNumber: 'LIC-454210',
    email: 'ops@natureharvest.in',
    phone: '+91 97665 78901',
    totalPurchases: '₹4.9L',
    totalSales: '₹6.4L',
    complaintCount: 1,
    registrationDate: '2025-02-15',
  },
  {
    id: 'CMP-601',
    name: 'AgriPure',
    location: 'Hyderabad, Telangana',
    rating: 4.3,
    status: 'Active',
    companyType: 'Distribution Partner',
    licenseNumber: 'LIC-233441',
    email: 'hello@agripure.in',
    phone: '+91 98440 77210',
    totalPurchases: '₹3.7L',
    totalSales: '₹5.1L',
    complaintCount: 3,
    registrationDate: '2025-03-26',
  },
];

export const priceMonitoring = [
  {
    crop: 'Basmati Rice',
    farmerPrice: '₹25',
    companyPurchase: '₹28',
    companySelling: '₹35',
    difference: '+₹10',
    farmerName: 'Rahul Verma',
    farmerLocation: 'Mysuru, Karnataka',
    companyName: 'GreenFresh Foods',
    transportation: '₹2',
    cleaning: '₹1',
    packaging: '₹1',
    storage: '₹1',
    otherCharges: '₹1',
    profitMargin: '₹5',
  },
  {
    crop: 'Tomatoes',
    farmerPrice: '₹18',
    companyPurchase: '₹22',
    companySelling: '₹27',
    difference: '+₹9',
    farmerName: 'Suma Nair',
    farmerLocation: 'Nedumangad, Kerala',
    companyName: 'NatureHarvest',
    transportation: '₹2',
    cleaning: '₹1',
    packaging: '₹1',
    storage: '₹1',
    otherCharges: '₹1',
    profitMargin: '₹4',
  },
  {
    crop: 'Maize',
    farmerPrice: '₹20',
    companyPurchase: '₹24',
    companySelling: '₹30',
    difference: '+₹10',
    farmerName: 'Karthik Rao',
    farmerLocation: 'Bellary, Karnataka',
    companyName: 'AgriPure',
    transportation: '₹2',
    cleaning: '₹1',
    packaging: '₹1',
    storage: '₹1',
    otherCharges: '₹1',
    profitMargin: '₹4',
  },
];

export const complaints = [
  {
    id: 'CMP-401',
    raisedBy: 'Farmer',
    against: 'GreenFresh Foods',
    type: 'Pricing Dispute',
    date: '2026-08-14',
    status: 'Pending' as ComplaintStatus,
    description: 'Delayed payment and incorrect procurement weight calculation.',
  },
  {
    id: 'CMP-412',
    raisedBy: 'Company',
    against: 'Rahul Verma',
    type: 'Quality Issue',
    date: '2026-08-18',
    status: 'In Progress' as ComplaintStatus,
    description: 'Reported difference in moisture content for rice batch.',
  },
  {
    id: 'CMP-423',
    raisedBy: 'Buyer',
    against: 'NatureHarvest',
    type: 'Delivery Delay',
    date: '2026-08-22',
    status: 'Resolved' as ComplaintStatus,
    description: 'Late shipment of tomatoes during supply window.',
  },
];

export const notifications = [
  { id: 'NT-501', title: 'Price Alert: Basmati Rice', type: 'Price Alert', date: '2026-08-20', status: 'Unread' as 'Unread' | 'Read' },
  { id: 'NT-510', title: 'New policy for digital verification', type: 'Policy Update', date: '2026-08-18', status: 'Read' as 'Unread' | 'Read' },
  { id: 'NT-520', title: 'Warning: Non-compliant company activity', type: 'Warning Notice', date: '2026-08-17', status: 'Unread' as 'Unread' | 'Read' },
  { id: 'NT-532', title: 'Company verification pending review', type: 'Company Verification Update', date: '2026-08-15', status: 'Read' as 'Unread' | 'Read' },
];

export const verificationRequests = [
  {
    id: 'VC-100',
    name: 'AgriVita Pvt Ltd',
    type: 'Food Processor',
    registrationDate: '2026-08-01',
    status: 'Pending',
    owner: 'Anil Menon',
    licenseNumber: 'LIC-775290',
    address: 'Coimbatore, Tamil Nadu',
    email: 'anil@agrivita.in',
    phone: '+91 94433 22011',
    documents: ['GST Certificate', 'Trade License', 'Farm Registration'],
  },
  {
    id: 'VC-115',
    name: 'Maharashtra Fresh Co.',
    type: 'Distributor',
    registrationDate: '2026-08-10',
    status: 'Pending',
    owner: 'Nisha Kulkarni',
    licenseNumber: 'LIC-149203',
    address: 'Pune, Maharashtra',
    email: 'nisha@maharashtrafresh.in',
    phone: '+91 98674 33452',
    documents: ['PAN Card', 'Company Incorporation', 'Address Proof'],
  },
];
